name: hornetsecurity-spam-malware-protection
pipeline:
  - name: parse_event
    external:
      name: json.parse-json
      properties:
        input_field: "{{original.message}}"
        output_field: "message"

  - name: parse_timestamp
    external:
      name: date.parse
      properties:
        input_field: "{{parse_event.message.date}}"
        output_field: date

  - name: set_base_fields

stages:
  set_base_fields:
    actions:
      - set:
          "@timestamp": "{{ parse_timestamp.date }}"

      - set:
          event.category: ["email"]
          event.type: ["info"]
          event.action: "No action"
          event.reason: "{{ parse_event.message.reason }}"

      - set:
          event.action: "{{ parse_event.message.last_remediation_actions[0] }}"
        filter: "{{ parse_event.message.last_remediation_actions | length > 0 }}"

      - set:
          email.from.address: ["{{ parse_event.message.owner}}"]
          email.to.address: ["{{ parse_event.message.comm_partner }}"]
          email.direction: "Outgoing"
        filter: "{{ parse_event.message.get('direction') != 1}}"

      - set:
          email.from.address: ["{{ parse_event.message.comm_partner}}"]
          email.to.address: ["{{ parse_event.message.owner }}"]
          email.direction: "Incoming"
        filter: "{{ parse_event.message.get('direction') == 1}}"

      - set:
          email.subject: "{{ parse_event.message.subject }}"
          email.message_id: "{{ parse_event.message.message_id }}"
          source.ip: "{{ parse_event.message.source_ip }}"
          destination.domain: "{{ parse_event.message.destination_domain }}"
          destination.ip: "{{ parse_event.message.destination_ip }}"

      - set:
          hornetsecurity.spam_malware_protection.classification: "{{ parse_event.message.classification.text | capitalize }}"
          hornetsecurity.spam_malware_protection.crypt_type_in: "{{ parse_event.message.crypt_type_in.text }}"
          hornetsecurity.spam_malware_protection.crypt_type_out: "{{ parse_event.message.crypt_type_out.text }}"
          hornetsecurity.spam_malware_protection.status: "{{ parse_event.message.status.text | capitalize }}"
          hornetsecurity.spam_malware_protection.source_hostname: "{{ parse_event.message.source_hostname }}"
          hornetsecurity.spam_malware_protection.destination_hostname: "{{ parse_event.message.destination_hostname }}"

          hornetsecurity.spam_malware_protection.private: "{{ parse_event.message.get('private', False) }}"
          hornetsecurity.spam_malware_protection.gateway: "{{ parse_event.message.gateway }}"
          hornetsecurity.spam_malware_protection.has_url_rewritten: "{{ parse_event.message.get('has_url_rewritten', False) }}"

      - set:
          hornetsecurity.spam_malware_protection.size: "Unknown"
      - set:
          hornetsecurity.spam_malware_protection.size: "{{ parse_event.message.size.value }} {{ parse_event.message.size.unit }}"
        filter: "{{ parse_event.message.size.get('value') != None and parse_event.message.size.get('unit') != None }}"

      - set:
          email.attachments: "{{ parse_event.message.attachments }}"
        filter: "{{ parse_event.message.attachments not in [null, '', 'no'] }}"
