name: Trigger a documentation rebuild

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: my-app-install token
        id: my-app
        uses: getsentry/action-github-app-token@v1
        with:
          app_id: ${{ secrets.DISPATCH_APP_ID }}
          private_key: ${{ secrets.DISPATCH_APP_SECRET_KEY }}

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ steps.my-app.outputs.token }}
          event-type: rebuild-intake-documentation
          repository: SEKOIA-IO/documentation/
